# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00ba37ea15a52464031c786f2b9e435476d5026e3101fe6fef842faaa15ee4d38d43d70150ae7beca05940e8bdd557e6afb412c8676400191cda47977fe6ccb7

test:
  secret_key_base: 2b392188e8b4d2515ab0316cb8107eb1413df7840cfe9a0724fc8fd1a7c0377a67c8701a84d8396963c57d7aecb5f425c0b70945c343a9d5ad24d64f0cb3b5ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
